# Options for analysis running.
run:
  # The default concurrency value is the number of available CPU.
  concurrency: 16
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
