tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
brew "automake"
brew "ccls"
brew "coreutils"
brew "ctop"
brew "openssl@1.1"
brew "curl"
brew "docker", link: false
brew "python@3.9"
brew "emscripten"
brew "flux", link: false
brew "fzf"
brew "gnupg"
brew "grep"
brew "htop"
brew "httpie"
brew "inetutils"
brew "jq"
brew "lastpass-cli"
brew "ldns"
brew "libxslt"
brew "libyaml"
brew "luajit", args: ["HEAD"]
brew "mas"
brew "neovim", args: ["HEAD"]
brew "ninja"
brew "openssh"
brew "perl"
brew "prettyping"
brew "python@3.8"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rsync"
brew "spark"
brew "ssh-copy-id"
brew "the_silver_searcher"
brew "transmission-cli"
brew "unixodbc"
brew "unzip"
brew "watch"
brew "zsh"
brew "qmk/qmk/qmk"
cask "alacritty"
cask "alfred"
cask "brave-browser"
cask "discord"
cask "docker"
cask "finicky"
cask "firefox"
cask "flux"
cask "google-chrome"
cask "keybase"
cask "ledger-live"
cask "mysqlworkbench"
cask "path-finder"
cask "rectangle"
cask "robo-3t"
cask "skype"
cask "slack"
cask "spotify"
cask "steam"
cask "telegram"
cask "the-unarchiver"
cask "toggl-track"
cask "transmission"
cask "tunnelblick"
cask "vlc"
mas "Clocker", id: 1056643111
mas "Keynote", id: 409183694
mas "Monosnap", id: 540348655
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
