tap "federico-terzi/espanso"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "jakehilborn/jakehilborn"
brew "libyaml"
brew "ansible"
brew "automake"
brew "glib"
brew "coreutils"
brew "gnutls"
brew "cask"
brew "ccache"
brew "llvm"
brew "ccls"
brew "cmake"
brew "libssh2"
brew "openldap"
brew "curl"
brew "dtc"
brew "emscripten"
brew "flux", link: false
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "gobject-introspection"
brew "grep"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "inetutils"
brew "jq"
brew "jump"
brew "lastpass-cli"
brew "ldns"
brew "libfido2"
brew "libxslt"
brew "luajit", args: ["HEAD"]
brew "mas"
brew "mmv"
brew "tree-sitter"
brew "neovim", args: ["HEAD"]
brew "nghttp2"
brew "openssh"
brew "pango"
brew "perl"
brew "pstoedit"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rsync"
brew "spark"
brew "ssh-copy-id"
brew "stow"
brew "terraform"
brew "tesseract"
brew "thefuck"
brew "tldr"
brew "unzip"
brew "watch"
brew "wget"
brew "wimlib"
brew "zsh"
brew "heroku/brew/heroku"
brew "jakehilborn/jakehilborn/displayplacer"
cask "alfred"
cask "android-file-transfer"
cask "brave-browser"
cask "docker"
cask "dozer"
cask "dropbox"
cask "finicky"
cask "flux"
cask "kitty"
cask "ledger-live"
cask "meetingbar"
cask "moom"
cask "path-finder"
cask "skype"
cask "slack"
cask "spotify"
cask "steam"
cask "telegram"
cask "the-unarchiver"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
mas "Clocker", id: 1056643111
mas "iStatistica Pro", id: 1447778660
mas "Keynote", id: 409183694
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "Tailscale", id: 1475387142
mas "Xcode", id: 497799835
