vim.api.nvim_set_hl(0, 'NormalFloat', {bg = 'none'})
vim.api.nvim_set_hl(0, 'FloatBorder', {bg = 'none'})
vim.api.nvim_set_hl(0, 'FoldColumn', {bg = 'none', fg = '#7E9CD8'})
vim.api.nvim_set_hl(0, 'LineNr', {bg = 'none'})
vim.api.nvim_set_hl(0, 'SignColumn', {bg = 'none'})
vim.api.nvim_set_hl(0, 'DiagnosticSignWarn', {bg = 'none'})
vim.api.nvim_set_hl(0, 'GitSignsChange', {bg = 'none'})
vim.api.nvim_set_hl(0, 'GitSignsAdd', {bg = 'none'})
vim.api.nvim_set_hl(0, 'GitSignsDelete', {bg = 'none'})
-- vim.api.nvim_set_hl(0, 'CursorLineNr', {bg = 'none'})
