# Enable Powerlevel10k instant prompt. Should stay close to the top of zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# zmodload zsh/zprof
source $HOME/.zsh_env
source $HOME/.zsh_prompt
source $HOME/.zsh_settings
source $HOME/.zsh_langs
source $HOME/.zsh_plugins
source $HOME/.zsh_aliases
source $HOME/.zsh_functions
source $HOME/.zsh_fzf
# zprof
